add_column <- function(dat = NULL, nominator = NULL, denominator = NULL){
    if (!is.null(dat) & !is.null(nominator) & !is.null(denominator)) {
        if(all(unique(c(nominator, denominator)) %in% colnames(dat))){
            nominator = sort(unique(nominator))
            denominator = sort(unique(denominator))
            dat = dat %>% mutate(newly_add_column = rowSums(.[nominator])/rowSums(.[denominator]))
            colnames(dat)[colnames(dat) == "newly_add_column"] = paste(
              paste(nominator, collapse = ""),
              paste(denominator, collapse = ""),
              sep = "_vs_"
            )
        }
    } else if(!is.null(dat) & !is.null(nominator) & is.null(denominator)){
        if(all(unique(nominator) %in% colnames(dat)) & length(unique(nominator))>1){
            nominator = sort(unique(nominator))
            dat = dat %>% mutate(newly_add_column = rowSums(.[nominator]))
            colnames(dat)[colnames(dat) == "newly_add_column"] = paste(nominator, collapse = "")
        }
    }
    return(dat)
}

keep_column <- function(dat = NULL, column = NULL){
    if(is.null(dat) | is.null(column)){
        return(NULL)
    }
    column = c(column, "Line", "line", "Taxa", "taxa", "Population", "population")
    index = NULL
    for(i in 1:length(column)){
        if(i == 1){
            index = str_detect(colnames(dat), column[i])
        } else{
            index = index | str_detect(colnames(dat), column[i])
        }
    }
    if(!is.null(index)){
        dat = dat[, index]
    }
    return(dat)
}



func_Glu_Fam <- function(dat = NULL, type = NULL){
    if(is.null(dat) | is.null(type)){
        return(NULL)
    }

    if(type == "FAA"){
        dat = add_column(dat, "E", "Total")
        dat = add_column(dat, "P", "Total")
        dat = add_column(dat, "R", "Total")
        dat = add_column(dat, "Q", "Total")
        dat = add_column(dat, "H", "Total")
        dat = add_column(dat, "E", "P")
        dat = add_column(dat, "E", "R")
        dat = add_column(dat, "E", "Q")
        dat = add_column(dat, "E", "H")
        dat = add_column(dat, "E", c("E", "P"))
        dat = add_column(dat, "E", c("E", "R"))
        dat = add_column(dat, "E", c("E", "Q"))
        dat = add_column(dat, "E", c("E", "H"))
        dat = add_column(dat, "E", c("P", "R"))
        dat = add_column(dat, "E", c("P", "Q"))
        dat = add_column(dat, "E", c("P", "H"))
        dat = add_column(dat, "E", c("R", "Q"))
        dat = add_column(dat, "E", c("R", "H"))
        dat = add_column(dat, "E", c("Q", "H"))
        dat = add_column(dat, "E", c("E", "P", "R"))
        dat = add_column(dat, "E", c("E", "P", "Q"))
        dat = add_column(dat, "E", c("E", "P", "H"))
        dat = add_column(dat, "E", c("E", "R", "Q"))
        dat = add_column(dat, "E", c("E", "R", "H"))
        dat = add_column(dat, "E", c("E", "Q", "H"))
        dat = add_column(dat, "E", c("P", "R", "Q"))
        dat = add_column(dat, "E", c("P", "R", "H"))
        dat = add_column(dat, "E", c("P", "Q", "H"))
        dat = add_column(dat, "E", c("R", "Q", "H"))
        dat = add_column(dat, "E", c("E", "P", "R", "Q"))
        dat = add_column(dat, "E", c("E", "P", "R", "H"))
        dat = add_column(dat, "E", c("E", "R", "Q", "H"))
        dat = add_column(dat, "E", c("P", "R", "Q", "H"))
        dat = add_column(dat, "E", c("E", "P", "R", "Q", "H"))
        dat = add_column(dat, "P", "E")
        dat = add_column(dat, "P", "R")
        dat = add_column(dat, "P", "Q")
        dat = add_column(dat, "P", "H")
        dat = add_column(dat, "P", c("E", "P"))
        dat = add_column(dat, "P", c("E", "R"))
        dat = add_column(dat, "P", c("E", "Q"))
        dat = add_column(dat, "P", c("E", "H"))
        dat = add_column(dat, "P", c("P", "R"))
        dat = add_column(dat, "P", c("P", "Q"))
        dat = add_column(dat, "P", c("P", "H"))
        dat = add_column(dat, "P", c("R", "Q"))
        dat = add_column(dat, "P", c("R", "H"))
        dat = add_column(dat, "P", c("Q", "H"))
        dat = add_column(dat, "P", c("E", "P", "R"))
        dat = add_column(dat, "P", c("E", "P", "Q"))
        dat = add_column(dat, "P", c("E", "P", "H"))
        dat = add_column(dat, "P", c("E", "R", "Q"))
        dat = add_column(dat, "P", c("E", "R", "H"))
        dat = add_column(dat, "P", c("E", "Q", "H"))
        dat = add_column(dat, "P", c("P", "R", "Q"))
        dat = add_column(dat, "P", c("P", "R", "H"))
        dat = add_column(dat, "P", c("P", "Q", "H"))
        dat = add_column(dat, "P", c("R", "Q", "H"))
        dat = add_column(dat, "P", c("E", "P", "R", "Q"))
        dat = add_column(dat, "P", c("E", "P", "R", "H"))
        dat = add_column(dat, "P", c("E", "R", "Q", "H"))
        dat = add_column(dat, "P", c("P", "R", "Q", "H"))
        dat = add_column(dat, "P", c("E", "P", "R", "Q", "H"))
        dat = add_column(dat, "R", "E")
        dat = add_column(dat, "R", "P")
        dat = add_column(dat, "R", "Q")
        dat = add_column(dat, "R", "H")
        dat = add_column(dat, "R", c("E", "P"))
        dat = add_column(dat, "R", c("E", "R"))
        dat = add_column(dat, "R", c("E", "Q"))
        dat = add_column(dat, "R", c("E", "H"))
        dat = add_column(dat, "R", c("P", "R"))
        dat = add_column(dat, "R", c("P", "Q"))
        dat = add_column(dat, "R", c("P", "H"))
        dat = add_column(dat, "R", c("R", "Q"))
        dat = add_column(dat, "R", c("R", "H"))
        dat = add_column(dat, "R", c("Q", "H"))
        dat = add_column(dat, "R", c("E", "P", "R"))
        dat = add_column(dat, "R", c("E", "P", "Q"))
        dat = add_column(dat, "R", c("E", "P", "H"))
        dat = add_column(dat, "R", c("E", "R", "Q"))
        dat = add_column(dat, "R", c("E", "R", "H"))
        dat = add_column(dat, "R", c("E", "Q", "H"))
        dat = add_column(dat, "R", c("P", "R", "Q"))
        dat = add_column(dat, "R", c("P", "R", "H"))
        dat = add_column(dat, "R", c("P", "Q", "H"))
        dat = add_column(dat, "R", c("R", "Q", "H"))
        dat = add_column(dat, "R", c("E", "P", "R", "Q"))
        dat = add_column(dat, "R", c("E", "P", "R", "H"))
        dat = add_column(dat, "R", c("E", "R", "Q", "H"))
        dat = add_column(dat, "R", c("P", "R", "Q", "H"))
        dat = add_column(dat, "R", c("E", "P", "R", "Q", "H"))
        dat = add_column(dat, "Q", "E")
        dat = add_column(dat, "Q", "P")
        dat = add_column(dat, "Q", "R")
        dat = add_column(dat, "Q", "H")
        dat = add_column(dat, "Q", c("E", "P"))
        dat = add_column(dat, "Q", c("E", "R"))
        dat = add_column(dat, "Q", c("E", "Q"))
        dat = add_column(dat, "Q", c("E", "H"))
        dat = add_column(dat, "Q", c("P", "R"))
        dat = add_column(dat, "Q", c("P", "Q"))
        dat = add_column(dat, "Q", c("P", "H"))
        dat = add_column(dat, "Q", c("R", "Q"))
        dat = add_column(dat, "Q", c("R", "H"))
        dat = add_column(dat, "Q", c("Q", "H"))
        dat = add_column(dat, "Q", c("E", "P", "R"))
        dat = add_column(dat, "Q", c("E", "P", "Q"))
        dat = add_column(dat, "Q", c("E", "P", "H"))
        dat = add_column(dat, "Q", c("E", "R", "Q"))
        dat = add_column(dat, "Q", c("E", "R", "H"))
        dat = add_column(dat, "Q", c("E", "Q", "H"))
        dat = add_column(dat, "Q", c("P", "R", "Q"))
        dat = add_column(dat, "Q", c("P", "R", "H"))
        dat = add_column(dat, "Q", c("P", "Q", "H"))
        dat = add_column(dat, "Q", c("R", "Q", "H"))
        dat = add_column(dat, "Q", c("E", "P", "R", "Q"))
        dat = add_column(dat, "Q", c("E", "P", "R", "H"))
        dat = add_column(dat, "Q", c("E", "R", "Q", "H"))
        dat = add_column(dat, "Q", c("P", "R", "Q", "H"))
        dat = add_column(dat, "Q", c("E", "P", "R", "Q", "H"))
        dat = add_column(dat, "H", "E")
        dat = add_column(dat, "H", "P")
        dat = add_column(dat, "H", "R")
        dat = add_column(dat, "H", "Q")
        dat = add_column(dat, "H", c("E", "P"))
        dat = add_column(dat, "H", c("E", "R"))
        dat = add_column(dat, "H", c("E", "Q"))
        dat = add_column(dat, "H", c("E", "H"))
        dat = add_column(dat, "H", c("P", "R"))
        dat = add_column(dat, "H", c("P", "Q"))
        dat = add_column(dat, "H", c("P", "H"))
        dat = add_column(dat, "H", c("R", "Q"))
        dat = add_column(dat, "H", c("R", "H"))
        dat = add_column(dat, "H", c("Q", "H"))
        dat = add_column(dat, "H", c("E", "P", "R"))
        dat = add_column(dat, "H", c("E", "P", "Q"))
        dat = add_column(dat, "H", c("E", "P", "H"))
        dat = add_column(dat, "H", c("E", "R", "Q"))
        dat = add_column(dat, "H", c("E", "R", "H"))
        dat = add_column(dat, "H", c("E", "Q", "H"))
        dat = add_column(dat, "H", c("P", "R", "Q"))
        dat = add_column(dat, "H", c("P", "R", "H"))
        dat = add_column(dat, "H", c("P", "Q", "H"))
        dat = add_column(dat, "H", c("R", "Q", "H"))
        dat = add_column(dat, "H", c("E", "P", "R", "Q"))
        dat = add_column(dat, "H", c("E", "P", "R", "H"))
        dat = add_column(dat, "H", c("E", "R", "Q", "H"))
        dat = add_column(dat, "H", c("P", "R", "Q", "H"))
        dat = add_column(dat, "H", c("E", "P", "R", "Q", "H"))
        dat = keep_column(dat, c("E", "P", "R", "Q", "H"))
        return(dat)
    } else if(type == "BAA"){
        dat = add_column(dat, "p", "total")
        dat = add_column(dat, "r", "total")
        dat = add_column(dat, "z", "total")
        dat = add_column(dat, "h", "total")
        dat = add_column(dat, "p", "r")
        dat = add_column(dat, "p", "z")
        dat = add_column(dat, "p", "h")
        dat = add_column(dat, "p", c("p", "r"))
        dat = add_column(dat, "p", c("p", "z"))
        dat = add_column(dat, "p", c("p", "h"))
        dat = add_column(dat, "p", c("r", "z"))
        dat = add_column(dat, "p", c("r", "h"))
        dat = add_column(dat, "p", c("z", "h"))
        dat = add_column(dat, "p", c("p", "r", "z"))
        dat = add_column(dat, "p", c("p", "r", "h"))
        dat = add_column(dat, "p", c("p", "z", "h"))
        dat = add_column(dat, "p", c("r", "z", "h"))
        dat = add_column(dat, "p", c("p", "r", "z", "h"))
        dat = add_column(dat, "r", "p")
        dat = add_column(dat, "r", "z")
        dat = add_column(dat, "r", "h")
        dat = add_column(dat, "r", c("p", "r"))
        dat = add_column(dat, "r", c("p", "z"))
        dat = add_column(dat, "r", c("p", "h"))
        dat = add_column(dat, "r", c("r", "z"))
        dat = add_column(dat, "r", c("r", "h"))
        dat = add_column(dat, "r", c("z", "h"))
        dat = add_column(dat, "r", c("p", "r", "z"))
        dat = add_column(dat, "r", c("p", "r", "h"))
        dat = add_column(dat, "r", c("p", "z", "h"))
        dat = add_column(dat, "r", c("r", "z", "h"))
        dat = add_column(dat, "r", c("p", "r", "z", "h"))
        dat = add_column(dat, "z", "p")
        dat = add_column(dat, "z", "r")
        dat = add_column(dat, "z", "h")
        dat = add_column(dat, "z", c("p", "r"))
        dat = add_column(dat, "z", c("p", "z"))
        dat = add_column(dat, "z", c("p", "h"))
        dat = add_column(dat, "z", c("r", "z"))
        dat = add_column(dat, "z", c("r", "h"))
        dat = add_column(dat, "z", c("z", "h"))
        dat = add_column(dat, "z", c("p", "r", "z"))
        dat = add_column(dat, "z", c("p", "r", "h"))
        dat = add_column(dat, "z", c("p", "z", "h"))
        dat = add_column(dat, "z", c("r", "z", "h"))
        dat = add_column(dat, "z", c("p", "r", "z", "h"))
        dat = add_column(dat, "h", "p")
        dat = add_column(dat, "h", "r")
        dat = add_column(dat, "h", "z")
        dat = add_column(dat, "h", c("p", "r"))
        dat = add_column(dat, "h", c("p", "z"))
        dat = add_column(dat, "h", c("p", "h"))
        dat = add_column(dat, "h", c("r", "z"))
        dat = add_column(dat, "h", c("r", "h"))
        dat = add_column(dat, "h", c("z", "h"))
        dat = add_column(dat, "h", c("p", "r", "z"))
        dat = add_column(dat, "h", c("p", "r", "h"))
        dat = add_column(dat, "h", c("p", "z", "h"))
        dat = add_column(dat, "h", c("r", "z", "h"))
        dat = add_column(dat, "h", c("p", "r", "z", "h"))
        dat = keep_column(dat, c("p", "r", "z", "h"))
        return(dat)
    }
    return(NULL)
}
